#!/usr/bin/env node
/**
 * Tools provenance report — every tool, where it lives (MCP system), what it
 * touches (tables), and how it is anchored to real research: the resolved
 * evidence items (kind, label, source URL) behind its anchor_refs, from the
 * world document's own research-anchor corpus.
 *
 * Output: docs/TOOLS.md
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const worldRaw = JSON.parse(readFileSync(join(ROOT, "world", "blobfish", "world-expanded.json"), "utf8"));
const world = worldRaw.world ?? worldRaw;
const systems = JSON.parse(readFileSync(join(ROOT, "mcp", "systems.json"), "utf8")).systems;

const anchorById = Object.fromEntries((world.anchors?.items ?? []).map((a) => [a.id, a]));
const toolSystem = {};
for (const [sys, spec] of Object.entries(systems)) for (const t of spec.tools) toolSystem[t] = sys;

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const kindCounts = {};
for (const a of world.anchors?.items ?? []) kindCounts[a.kind ?? "?"] = (kindCounts[a.kind ?? "?"] ?? 0) + 1;

const md = [];
md.push("# Tools — inventory and research anchoring");
md.push("");
md.push(`All ${world.tools.length} executable tools, grouped by the MCP system that serves them`);
md.push("(`mcp/systems.json`, one server per firm product), with each tool's research anchoring");
md.push("resolved from the world document's evidence corpus: " +
  `**${(world.anchors?.items ?? []).length} evidence items** collected by ` +
  `**${(world.anchors?.executed_search_queries ?? world.anchors?.search_queries ?? []).length} live research queries** at generation time ` +
  `(kinds: ${Object.entries(kindCounts).map(([k, n]) => `${k}×${n}`).join(", ")}).`);
md.push("");
md.push("**Honesty box.** Anchoring strength varies and is stated per tool:");
md.push(`${world.tools.filter((t) => (t.anchor_refs ?? []).length).length}/${world.tools.length} tools carry`);
md.push("resolvable anchor evidence; the rest are runtime/CRUD surfaces admitted by execution");
md.push("testing only. The original generation's own scorecard flagged research-angle breadth 4/12 —");
md.push("the base world's grounding is real but partial. The expansion packs' anchoring is separate");
md.push("and stronger: every expansion task cites its benchmark (CUAD/MAUD/LegalBench/BigLaw/");
md.push("TaxCalcBench/Stanford-HAI/court-rules) with the vendored source read at authoring time");
md.push("(`data/research/legal-eval-inventory.md`), and each task's `provenance.source_workflow`");
md.push("names its anchor. The sales world raises this bar further: tools mocked 1:1 from real");
md.push("product APIs/MCP docs (`docs/SALES-WORLD-DESIGN.md` §2).");
md.push("");

for (const [sys, spec] of Object.entries(systems)) {
  md.push(`## ${sys} — ${esc(spec.product)}`);
  md.push("");
  md.push(esc(spec.description));
  md.push("");
  md.push("| Tool | Type | Tables | Research anchoring |");
  md.push("|---|---|---|---|");
  for (const name of spec.tools) {
    const tool = world.tools.find((t) => t.name === name);
    if (!tool) continue;
    const refs = (tool.anchor_refs ?? []).map((id) => anchorById[id]).filter(Boolean);
    const shown = refs.slice(0, 3).map((a) =>
      a.source_url ? `[${esc(a.label ?? a.id)}](${a.source_url})` : esc(a.label ?? a.id));
    const anchoring = refs.length
      ? `${shown.join("; ")}${refs.length > 3 ? ` (+${refs.length - 3} more)` : ""}`
      : "*execution-tested only (no research anchors)*";
    md.push(`| \`${name}\` | ${tool.type} | ${esc((tool.target_tables ?? []).slice(0, 3).join(", "))}${(tool.target_tables ?? []).length > 3 ? "…" : ""} | ${anchoring} |`);
  }
  md.push("");
}

md.push("## The evidence corpus itself");
md.push("");
md.push("| Kind | Items | Examples |");
md.push("|---|---|---|");
for (const [kind, n] of Object.entries(kindCounts).sort((a, b) => b[1] - a[1])) {
  const ex = (world.anchors?.items ?? []).filter((a) => (a.kind ?? "?") === kind).slice(0, 3)
    .map((a) => a.source_url ? `[${esc(a.label ?? a.id)}](${a.source_url})` : esc(a.label ?? a.id));
  md.push(`| ${kind} | ${n} | ${ex.join("; ")} |`);
}
md.push("");
md.push("*Generated by `node world/expansion/tools-report.mjs` from the world document — every*");
md.push("*anchor id above resolves to a fetched evidence item with a content hash and timestamp.*");

writeFileSync(join(ROOT, "docs", "TOOLS.md"), md.join("\n") + "\n");
const anchored = world.tools.filter((t) => (t.anchor_refs ?? []).length).length;
console.log(`TOOLS.md: ${world.tools.length} tools across ${Object.keys(systems).length} systems, ${anchored} research-anchored, ${(world.anchors?.items ?? []).length} evidence items`);
