#!/usr/bin/env node
/**
 * Current product-tool inventory.
 *
 * The Gen-1 research-anchor report formerly generated here described the
 * retired synthesized surface.  This report is compiled from the MCP
 * partition and fail-closed conformance artifact instead.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const systems = JSON.parse(readFileSync(join(ROOT, "mcp", "systems.json"), "utf8")).systems;
const conformance = JSON.parse(readFileSync(join(ROOT, "data", "conformance.json"), "utf8"));
const rows = Object.fromEntries(conformance.tools.map((tool) => [tool.name, tool]));
const summary = conformance.summary;

const md = [
  "# Tools — product inventory and conformance",
  "",
  `The evaluated surface contains **${summary.contract_tools} agent-visible tools across ${Object.keys(systems).length} mirrored products**.`,
  "Every name is partitioned exactly once by `mcp/systems.json`; simulator-only actuators are excluded from MCP discovery.",
  "Request, response, pagination, error, live-diff, and fidelity-ceiling evidence is generated by `tools/conformance/`.",
  "",
  `- ${summary.exact_vendor_tools}/${summary.contract_tools} are exact to a pinned machine-readable public contract.`,
  `- ${summary.verification_passed_vendor_tools}/${summary.publicly_verifiable_vendor_tools} pass the best public verification available.`,
  `- ${summary.contract_tools - summary.publicly_verifiable_vendor_tools} iManage operations remain explicitly partner-gated.`,
  `- ${summary.simulator_extension_gaps} agent-visible simulator-extension gaps; ${summary.harness_failures} conformance-harness failures.`,
  "",
  "See [the conformance matrix](CONFORMANCE.md), [product justification](MCP-JUSTIFICATION.md), and [generated API pages](api/V3-README.md).",
  "",
];

for (const [system, spec] of Object.entries(systems)) {
  md.push(`## ${system} — ${spec.product}`, "", spec.description, "");
  md.push("| Tool | Mirrored operation | Verification |", "|---|---|---|");
  for (const name of spec.tools) {
    const tool = rows[name];
    if (!tool) throw new Error(`conformance row missing for ${name}`);
    md.push(`| \`${name}\` | ${String(tool.mirror ?? "").replace(/\|/g, "\\|")} | ${tool.status} |`);
  }
  md.push("");
}

md.push("*Generated by `node world/expansion/tools-report.mjs` from `mcp/systems.json` and `data/conformance.json`.*", "");
writeFileSync(join(ROOT, "docs", "TOOLS.md"), md.join("\n"));
console.log(`TOOLS.md: ${summary.contract_tools} agent tools across ${Object.keys(systems).length} systems`);
